name: "Zac Halbert"
description: "Portfolio and blog of product designer Zac Halbert. Thoughts about product design, startups, and moving people forward with technology."
url: "http://www.zachalbert.com"
markdown: kramdown
highlighter: pygments
exclude: ["node_modules", "bower_components", "gulpfile.js", "package.json", "bower.json", "README.md"]
excerpt_separator: "<!-- more -->"
permalink: /:title
paginate: 5
paginate_path: "/p:num"
gems:
  - jekyll-sitemap
